# azure-pipelines.yml
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'webconferenciacarga'
  # seu usuário do Docker Hub (troque abaixo)
  dockerHubRepo: 'pedrodagostini/webconferenciacarga'
  tag: '$(Build.BuildNumber)'
  # Azure
  azureServiceConnection: 'AzureRM-Connection'
  resourceGroup: 'Datasite'
  webAppName: 'webconferenciacarga-app'
  # Docker Hub service connection
  dockerServiceConnection: 'DockerHubConnection'

stages:
  - stage: Build_and_Push
    displayName: Build & Push Docker
    jobs:
      - job: BuildPush
        displayName: Build and push to Docker Hub
        steps:
          - checkout: self
          - task: Docker@2
            displayName: Build and push
            inputs:
              command: 'buildAndPush'
              repository: '$(dockerHubRepo)'
              dockerfile: 'Dockerfile'
              containerRegistry: '$(dockerServiceConnection)'
              tags: |
                $(tag)
                latest

  - stage: Deploy
    displayName: Deploy to Azure Web App (Container)
    dependsOn: Build_and_Push
    jobs:
      - job: DeployJob
        displayName: Configure Web App to use the image
        steps:
          - task: AzureCLI@2
            displayName: 'Configure container on Web App'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e

                APP_NAME="$(webAppName)"
                RG="$(resourceGroup)"
                IMAGE="$(dockerHubRepo):$(tag)"

                echo "Setting container image to $IMAGE"
                az webapp config container set \
                  --name "$APP_NAME" \
                  --resource-group "$RG" \
                  --docker-custom-image-name "$IMAGE" \
                  --docker-registry-server-url "https://index.docker.io/v1/"

                echo "Ensuring WEBSITES_PORT=80"
                az webapp config appsettings set \
                  --name "$APP_NAME" \
                  --resource-group "$RG" \
                  --settings WEBSITES_PORT=80

                echo "Restarting Web App"
                az webapp restart --name "$APP_NAME" --resource-group "$RG"
